spring.application.name=feedback-service
gemini.api.key=AIzaSyAh70YP_tV0yq64HRQa0scd4zMKZkqTvRQ

# Logging configuration
logging.level.com.retailstore=DEBUG
logging.level.org.springframework.web=INFO

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML